### ISSUE TITLE
Explanation needed

### ISSUE THREAD

**Issue by jimmiles** [Tropfchen/ComfyUI-Embedding_Picker#1]
Love the concept. But the node has "prompts" on either end, which connect to each other, and no clear explanation what to connect it in between. Sample workflow image won't import, and the nodes in it aren't in my Comfy.

**Comment by Tropfchen** [comment]
Node accepts and simply outputs just text, but it is indeed confusing situation. ~~After I have added quick nodes, I wanted for the node itself to have Multiline Text widget,
which I think would also solve this confusion, trouble is, it would be a breaking change to existing workflows.~~

After working with the widget's multiline version for a few days, I decided to release the update. Let me know if it also resolves all of your concerns.


As for sample workflow image, it should now import fine.
